### ISSUE TITLE
アカウントを削除できるように

### ISSUE THREAD

**Issue by Matsushin** [Matsushin/qiitan#4]
レコードを物理削除ではなく論理削除にしたい

**Comment by Cawaz** [comment]
タスクばらし
- gem `paranoia`をインストール
  - `delete_flg`カラムを追加
- viewにアカウント削除ボタン配置
- controller
- routing
- feature spec

**Comment by Cawaz** [comment]
# 本家
## アカウント設定画面
![ScreenShot 2019-07-21 20 42 24](https://user-images.githubusercontent.com/47560224/61590866-ae3dc180-abf9-11e9-8cbe-cfadb038dd95.jpg)

## 削除確認画面
- 退会ボタン押下後の確認ダイアログはなし
![ScreenShot 2019-07-21 20 41 59](https://user-images.githubusercontent.com/47560224/61590878-c6154580-abf9-11e9-96dd-3ce46d601fa8.jpg)

## 削除完了画面
![ScreenShot 2019-07-21 20 50 27](https://user-images.githubusercontent.com/47560224/61590881-cf9ead80-abf9-11e9-8d3c-64b1c4e16564.jpg)

**Comment by Cawaz** [comment]
Problems
~~- `退会する`ボタンを押した時のhttpメソッドが、`delete`ではなく`patch`になってしまう~~
- 入力したパスワード判定ロジック
  - 編集の使い回し難しい？
- 削除確認画面のレイアウトが崩れる。
  - グリッドシステムが効いてない？
  - divはブロック要素なのに横並びになる。
