### ISSUE TITLE
トップにQiitaのようにアカウント情報を表示する

### ISSUE THREAD

**Issue by Matsushin** [Matsushin/qiitan#58]
こんな風にしたい。フォロワー情報は表示できない
<img width="1238" alt="Qiita" src="https://user-images.githubusercontent.com/592230/70052720-3e176180-1617-11ea-8663-26d887ce3f77.png">

**Comment by 1112hiroki** [comment]
![image](https://user-images.githubusercontent.com/57358551/71404742-b43b4100-2676-11ea-989c-e0ae65a7ccb9.png)

**Comment by Matsushin** [comment]
確認できたので閉じる
