### ISSUE TITLE
自分の記事にいいねできないように

### ISSUE THREAD

**Issue by Matsushin** [Matsushin/qiitan#7]

**Comment by Cawaz** [comment]
タスクバラし
- [ ] サーバーサイドで自分の記事にいいねをできないようにするロジックを組む
  - [ ] いいねボタンをクリックしてもlikeテーブルにレコードが作成されないことをテストする
- [ ] いいねボタンにカーソルを置くと、カーソルに禁止マークが表示されるようにする
- [ ] Tabでいいねボタンを選択した際に、青枠が表示されないようにする

**Comment by Cawaz** [comment]
テストのタスクばらし

- ユーザ１でログインする
  - ユーザ１で記事を作成する
  - ログアウトする
- ユーザ２でログインする
  - ユーザ２で記事を作成する
  - ユーザ２の記事にいいねができない
  - ユーザ１の記事にいいねができる

**Comment by Cawaz** [comment]
マージ完了
